spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/data_jpa
        username: postgres
        password: secret1234
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        defer-datasource-initialization: true

grpc:
    server:
        port: 6565